language: cpp
compiler:
  - gcc
  - clang
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - cmake
    - fglrx
    - opencl-headers
before_script:
  - mkdir install
  - export PATH=`pwd`/install/bin:${PATH}
  - export LD_LIBRARY_PATH=`pwd`/install/lib64:`pwd`/install/lib:${LD_LIBRARY_PATH}
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=../install ..
script:
  - make
  - make install
notifications:
  email: false
sudo: false
