language: cpp
sudo: required
dist: trusty

addons:
  apt:
    sources:
      # kubuntu-backports contains newer versions of cmake to install
      - kubuntu-backports
    packages:
      - cmake
      - ocl-icd-opencl-dev

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx

env:
  global:
    - CLBLAST_ROOT=${TRAVIS_BUILD_DIR}/bin/clblast

before_install:
  - cmake --version;
  - ${CC} --version;
  - ${CXX} --version;

before_script:
  - mkdir -p ${CLBLAST_ROOT}
  - pushd ${CLBLAST_ROOT}
  - cmake -DTESTS=ON -DCLIENTS=ON -DSAMPLES=ON -DNETLIB=ON ${TRAVIS_BUILD_DIR}

script:
  - make

branches:
  only:
    - master

notifications:
  email: false
